import {
  AcademicCapIcon,
  Cog6ToothIcon,
  HomeIcon,
} from "@heroicons/react/24/solid";
import {
  CoinsList,
  DailySummaryData,
  NavLinks,
  OrderBook,
} from "@/lib/typings";
import {
  BadgeIcon,
  ChartBarIcon,
  Clock,
  Currency,
  DownloadIcon,
  PlusIcon,
  Table,
} from "lucide-react";

export const navLinks: NavLinks[] = [
  { Icon: HomeIcon, title: "Dashboard", url: "/" },

  { Icon: Table, title: "Orders List", url: "/orders-list" },
  { Icon: Currency, title: "Payouts", url: "/payouts" },
  { Icon: AcademicCapIcon, title: "Certificates", url: "/certificates" },
  { Icon: ChartBarIcon, title: "Analytics", url: "/analytics" },
  { Icon: Cog6ToothIcon, title: "Settings", url: "/settings" },
  { Icon: PlusIcon, title: "Open a Trade", url: "/upload-trade" },
  { Icon: DownloadIcon, title: "Log a Trade", url: "/log-trade" },
];

export const topRowData = [
  { title: "Realized PnL($)", Icon: BadgeIcon, value: "798.48USDT" },
  {
    title: "Win Rate",
    Icon: BadgeIcon,
    value: "46.36%",
  },
  { title: "Risk Factors", Icon: BadgeIcon, value: "+12.8R" },
  {
    title: "Average Holding Time",
    Icon: Clock,
    value: "2hrs, 15min",
  },
];
export const dailySummaryData: DailySummaryData[] = [
  {
    date: "01/30",
    coinTicker: "SOLUSDT.P",
    risk: 50,
    direction: "long",
    image: "/assets/profile-pic.webp",
    entryPrice: 85958,
    exitPrice: 484985,
    riskFactors: 4,
    timeWindow: "Zone 4",
    divergence: true,
    headAndShoulders: true,
    proTrendBias: false,
    trades: 316,
    trendlineRetest: true,
    winRate: 72,
    realizedPnL: 357.86,
    roi: 2,
    equity: 55885,
    id: 1,
  },
  {
    date: "01/30",
    coinTicker: "SOLUSDT.P",
    risk: 50,
    direction: "long",
    image: "/assets/profile-pic.webp",
    entryPrice: 85958,
    exitPrice: 484985,
    riskFactors: 4,
    timeWindow: "Zone 4",
    divergence: true,
    headAndShoulders: true,
    proTrendBias: false,
    trades: 316,
    trendlineRetest: true,
    winRate: 72,
    realizedPnL: 357.86,
    roi: 2,
    equity: 55885,
    id: 1,
  },
  {
    date: "01/30",
    coinTicker: "SOLUSDT.P",
    risk: 50,
    direction: "long",
    image: "/assets/profile-pic.webp",
    entryPrice: 85958,
    exitPrice: 484985,
    riskFactors: 4,
    timeWindow: "Zone 4",
    divergence: true,
    headAndShoulders: true,
    proTrendBias: false,
    trades: 316,
    trendlineRetest: true,
    winRate: 72,
    realizedPnL: 357.86,
    roi: 2,
    equity: 55885,
    id: 1,
  },
  {
    date: "01/30",
    coinTicker: "SOLUSDT.P",
    risk: 50,
    direction: "long",
    image: "/assets/profile-pic.webp",
    entryPrice: 85958,
    exitPrice: 484985,
    riskFactors: 4,
    timeWindow: "Zone 4",
    divergence: true,
    headAndShoulders: true,
    proTrendBias: false,
    trades: 316,
    trendlineRetest: true,
    winRate: 72,
    realizedPnL: 357.86,
    roi: 2,
    equity: 55885,
    id: 1,
  },
];

export const pnlOverTimeChartData = [
  { month: "January", gains: 186, losses: 80 },
  { month: "February", gains: 305, losses: 200 },
  { month: "March", gains: 237, losses: 120 },
  { month: "April", gains: 73, losses: 190 },
  { month: "May", gains: 209, losses: 130 },
  { month: "June", gains: 214, losses: 140 },
];

export const listOfCoins: CoinsList[] = [
  { name: "BTC/USDT", logo: "/assets/Bitcoin.png", value: "btcusdt" },
  { name: "1000PEPE/USDT", logo: "/assets/Pepe.png", value: "1000pepeusdt" },
  { name: "SOL/USDT", logo: "/assets/Solana.webp", value: "solusdt" },
  { name: "AVAX/USDT", logo: "/assets/Avax.png", value: "avaxusdt" },
];

export const leverageAmount: string[] = [
  "5x",
  "10x",
  "15x",
  "20x",
  "25x",
  "30x",
  "45x",
  "50x",
  "75x",
  "80x",
  "95x",
  "100x",
  "125x",
  "150x",
  "175x",
  "200x",
];

export const orderBook: OrderBook[] = [
  {
    coinSymbol: {
      coinLogo: "/btc.png",
      coinName: "btc",
      coinDesc: "Bitcoin TetherUS PERPETUAL",
    },
    screenshot: "/mockup.png",
    date: "24 Aug 2025",
    status: "win",
    type: "buy",
    PnL: "250.00",
    accountType: "Prop Firm",
    session: "Asian Session",
    entryPrice: 10000,
    stopLoss: 10000,
    takeProfit: 10000,
    positionSize: 189498,
    strategy: {
      divergence: true,
      h_s: true,
      trendLineRetest: false,
      proTrendBias: false,
      fibKeyLevels: false,
    },
    confidenceLevel: 3,
  },
];
